### ISSUE TITLE
`contains` and `remove` work differently than documented

### ISSUE THREAD

**Issue by j-w-shin** [Stoeoef/rstar#12]
It appears that `==` is technically not the only criterion required for the `remove` methods of `RTree<T>`. The passed-in `&T` also needs to hold the same envelope, otherwise `remove` cannot continue the tree traversal.

https://github.com/Stoeoef/rstar/blob/26e4d86987ff922bd705f1ae77a3c1b1903a3f3c/rstar/src/algorithm/removal.rs#L15-L22

where `should_unpack_parent` is

https://github.com/Stoeoef/rstar/blob/26e4d86987ff922bd705f1ae77a3c1b1903a3f3c/rstar/src/algorithm/selection_functions.rs#L140-L146

A similar issue exists with `contains`. The documentation should probably be updated to reflect this.

**Comment by Stoeoef** [comment]
Indeed, the removal lookup assumes that `a == b` implies `a.envelope() == b.envelope()`, which is - strictly spoken - not required for a correct `==` implementation. Is this what you mean? I did not include this assumption in the documentation as I could not envision a scenario where this would not hold. Let me know if I overlooked something.

Adding a sentence like

> This method will work only correctly if two equal (`==`) elements also have the same envelope.

to `remove` and `contains` should be enough to mitigate this I believe.

Other than that, thanks for the report - please let me know if I understood you correctly and if there's anything to add from your point of view.

**Comment by j-w-shin** [comment]
Right. I could imagine a scenario where the user doesn't have access to a reference of the original node that they want to remove, so they might try instantiating a new dummy node that is `eq` to the node and passing that in instead.

But yeah, I got confused by this, would be nice to have a line about it somewhere.

**Comment by Stoeoef** [comment]
Ah, this sounds plausible. Sure, I'll add this with the next release!

**Comment by Stoeoef** [comment]
Argh, dumb me has forgot to include this in version 0.5.0 - this will have to wait for 0.6.0 or 0.5.1, whatever is next. This is fixed on `master` though. Thanks for the report!

**Comment by j-w-shin** [comment]
No worries at all, thanks for the version bump!
