### ISSUE TITLE
Associating values with points: trouble with generate

### ISSUE THREAD

**Issue by crclark** [Stoeoef/rstar#15]
I would like to associate extra data with each point I insert, so I am defining a struct like

```rust
pub struct MyPoint<T> {
    pub x: f32,
    pub y: f32,
    pub v: T
}
```

The trouble is that when implementing `Point` for this type, I need to implement `generate`, which wants me to create a `T` from nothing. When `T` is some opaque type from a library I don't control, it can be impossible to implement `generate`. 

Would it be possible to drop `generate` from the `Point` trait? If not, could the `RTree` API itself allow us to associate a value with each point? In the meantime, my workaround is to wrap `T` in `Option`, but that is a bit messy.

**Comment by Stoeoef** [comment]
To associate data with a point, implement [`RTreeObject`](https://docs.rs/rstar/0.5.1/rstar/trait.RTreeObject.html) instead. There is an example attached that looks pretty much like your source code.

Thanks for the question, I think I need to make the documentation more specific and maybe add a
```Rust
struct PointWithData<P: Point, D> {
  point: P,
  data: D
}
impl<P, D> RTreeObject for PointWithData [...]
```
in the future.

**Comment by crclark** [comment]
Oops, looks like I missed `RTreeObject`. Thanks!

**Comment by donpdonp** [comment]
I ran into the same problem. Having Point support [f32; 2] is great but I imagine the most common use case is, once I found the nearest point/rectangle, I need an index into another database to look that up. In my case, an openstreetmap object id.

**Comment by Stoeoef** [comment]
I've added a `PointWithData` struct in 0.6.0 and adjusted the `Point` documentation a bit. Hope that helps!
