### ISSUE TITLE
Push code for 0.6.0 to GitHub

### ISSUE THREAD

**Issue by ckaran** [Stoeoef/rstar#20]
It looks like while you've release 0.6.0, you haven't pushed the code to GitHub yet; could you please push it?

**Comment by Stoeoef** [comment]
Whoops, you are totally right - my bad. TIL: `git push origin 0.6.0` does *not* update the master. The tag was there, though :) . Yikes!

**Comment by ckaran** [comment]
Huh, I would have thought that command would have worked too! Oh well, it's there now, thank you! :)
