### ISSUE TITLE
AABB broken link in documentation

### ISSUE THREAD

**Issue by Dushistov** [Stoeoef/rstar#4]
On page
https://docs.rs/rstar/0.2.0/rstar/trait.RTreeObject.html

there is link to AABB:

https://docs.rs/rstar/0.2.0/rstar/structs.AABB.html

which is broken, should be 

https://docs.rs/rstar/0.2.0/rstar/struct.AABB.html

**Comment by Stoeoef** [comment]
Thanks for the report!
