### ISSUE TITLE
Documentation should indicate that removal is O(N)

### ISSUE THREAD

**Issue by code-affinity** [Stoeoef/rstar#47]
All of the removal functions use the lower-level helper function RTree::remove_with_selection_function, which simply depth-first searches the entire tree until it finds a node that matches the selection criteria.  Even when the selection function is a point coordinate (i.e. RTree::remove_at_point), this search does not take advantage of the spatial properties of the RTree data structure, so it is an O(N) operation.

Even the function RTree::pop_nearest_neighbor, which performs a R-tree optimized search query and then immediately deletes the corresponding node, does not take advantage of the optimized query results when removing the node -- it resorts to another O(N) search to remove the node.

I am not claiming that this implementation is incorrect, but I think this is an important performance characteristic that should be documented.

As an example of the consequences of this performance characteristic, my use case was essentially to implement a solution to the Traveling Salesman problem.  I'm optimizing the traversal of a large collection of vector shapes.  I can start the path traversal from many different positions over time, so the tradeoff of one-time tree construction time for repeated fast queries makes sense.  In pseudo-code form, my algorithm is:

```
clone the tree
current point = some initial point
path = empty list
while (cloned tree not empty) {
    current point = nearest neighbor to current point
    add the current point to the path
    remove the current point from the cloned tree
}
```

Having an O(N) operation inside this loop defeats my purpose.  If I had known that the removal function was O(N), I would have chosen a different solution.  Again, I'm not saying that the rstar code should change, only that the documentation should describe the performance so that people can make an informed decision if it is suitable to their application.

(I concede that the need to clone the tree may also be a good reason to look for a different solution to my problem.)

I don't think the node removal problem is unique to the rstar crate.  Now that I'm alert to this factor, I've surveyed other crates that implement spatial data structures.

Most other spatial data structure crates simply don't support node removal at all (acacia, quadtree-cd, gaia_quadtree, ntree, fart-aabb).  

Two crates (quadtree_rs and aabb-quadtree) provide for node removal.  They both improve the performance of node removal somewhat by identifying tree items with a unique numeric handle.  Items are stored in a hash map using the item handle as a key, so node removal has the performance of the hash_map.  The spatial data structures themselves do not hold the items; they only item handles.  This is a big tradeoff.  Item lookup with this crates entails not only a spatial query, but a hash_map query.

**Comment by Stoeoef** [comment]
Thanks for the report.
To my knowledge removal is in `O(log(n))`.
Have a look at removal.rs:
https://github.com/Stoeoef/rstar/blob/47efe5136b75307ed5e308cdceea0f18bc20e42a/rstar/src/algorithm/removal.rs#L22 

The `should_unpack_parent` function will frequently return `false` depending on the bounding box of the element to be removed, pruning uninteresting branches early.
Please let me know if I've overlooked something there or if your benchmarks show a runtime of `O(n)`.

That being said, the removal function as of now is far from optimal. Frequent removals and insertions can degrade the quality of the rtree significantly as no balancing is performed. That's just an FYI though, unrelated to the topic at hand.

**Comment by code-affinity** [comment]
I'm sorry; you are correct.  Studying the interaction between the SelectionFunctions and the remove function, I see now how the search for the item to remove does indeed utilize the spatial search capabilities.  Somehow I missed the fact that the SelectionFunction structs all have an RTreeObject member that has an envelope that guides the search process during removal.

In fact, I think all of your removal approach is superior to those implemented by the two crates I cited at the end of my opening note, since theirs require both a tree search *and* a hash_map lookup for each removal.

For my use case, I do not mix node insertions and removals, so I don't think tree balance will be a problem.

Thank you for your patient response.  I apologize for the annoyance this must have caused you.

**Comment by Stoeoef** [comment]
No apology required. I'm quite happy if other people read through my code and try to find errors or improvements.
Good luck with your project!
