### ISSUE TITLE
Expose the length of a `Line`

### ISSUE THREAD

**Issue by varkor** [Stoeoef/rstar#8]
It would be useful to have an analogue of [`SimpleEdge::length2`](https://docs.rs/spade/1.7.0/spade/primitives/struct.SimpleEdge.html#method.length2) for `Line`.

**Comment by Stoeoef** [comment]
Yep, that seems to be an oversight when porting over the spade pritmitives - thanks for the report!

**Comment by Stoeoef** [comment]
Fixed with b704cb6
